apiVersion: v1
description: Deploy a single-node non-HA Solace PubSub+ Event Broker Software onto
  a Kubernetes Cluster
home: https://dev.solace.com
icon: https://solaceproducts.github.io/pubsubplus-kubernetes-quickstart/images/PubSubPlus.png
keywords:
- solace
- pubsubplus
- pubsub+
- pubsub
- messaging
- advanced event broker
- event broker
- event mesh
- event streaming
- data streaming
- event integration
- middleware
maintainers:
- name: Solace Community Forum
  url: https://solace.community/
- name: Solace Support
  url: https://solace.com/support/
name: pubsubplus
sources:
- https://github.com/SolaceProducts/pubsubplus-kubernetes-quickstart
version: 2.1.2.1
